### ISSUE TITLE
OscOS can crash if bufloc is too close to 1.0

### ISSUE THREAD

**Issue by jamshark70** [spluta/OversamplingOscillators#2]
```
(
s.waitForBoot {
	// empirically, each waveform is 2048 samples
	// the file has 256 tables = 524288 samples total
	// source: VCV Rack 2: Blamsoft XFX Wave plugin
	b = Buffer.read(s, "~/.local/share/Rack2/plugins-lin-x64/Blamsoft-XFXWave/res/XTable Growler.wav".standardizePath);

	s.sync;

	a = {
		var freq = MouseX.kr(50, 3000, 1);
		var phase = Phasor.ar(0, freq * SampleDur.ir, 0, 1);
		var wtpos = (SinOsc.kr(0.08) * 0.5 + 0.5).poll(100);
		(OscOS.ar(b, phase, b.numFrames / 2048, wtpos, 3)
			* 0.2).dup
	}.play;
};
)
```

When `SinOsc.kr(0.08) * 0.5 + 0.5` exceeds 0.999034 (last poll value), the server segfaults in OscOS::Perform.

`SinOsc.kr(0.08) * 0.49 + 0.5` is no problem.

**Comment by spluta** [comment]
I can't replicate the issue. The bufloc is clipped internally, so it shouldn't have this issue. I wonder if I fixed this since you downloaded the library?

Do you have the same issue with OscOS3:

```
(
    s.waitForBoot {
        // empirically, each waveform is 2048 samples
        // the file has 256 tables = 524288 samples total
        // source: VCV Rack 2: Blamsoft XFX Wave plugin
        b = Buffer.read(s, "~/.local/share/Rack2/plugins-lin-x64/Blamsoft-XFXWave/res/XTable Growler.wav".standardizePath);
    
        s.sync;
    
        a = {
            var freq = MouseX.kr(50, 3000, 1);
            var wtpos = SinOsc.kr(0.08).range(0,1).poll(100);
            (OscOS3.ar(b, -1, freq, 0, 0, b.numFrames / 2048, wtpos, 1, 0, 1, 0, 3)
                * 0.2).dup
        }.play;
    };
)
```
I would recommend using OscOS3 in all cases anyway, as it uses an internal phasor, but can read over a variable phasor if you want to warp the wavetable. You don't need to make a mipmap to use it. You just use it like above. But the mipmap feature allows you to playback without any foldover at all speeds.

**Comment by dietcv** [comment]
it seems that i can confirm that issue, when setting buf_loc to 1 initially: 

```
(
{
	var phase, sig;
	
	phase = Phasor.ar(0, 100 * SampleDur.ir);
	sig = OscOS.ar(
		bufnum: b,
		phase: phase,
		buf_divs: b.numFrames / 2048,
		buf_loc: 1,
		oversample: 2
	);
	
	sig!2 * 0.1;
}.play;
)
```

 i get:

```
Server 'localhost' exited with exit code -1073741819.
server 'localhost' disconnected shared memory interface
```

however enabling modulation from an LFO going from 0 to 1, when the Synth is already running, doesnt throw an error:

```
(
x = {
	var phase, sig, tableIndex;
	
	tableIndex = SinOsc.ar(0.3).linlin(-1, 1, 0, \modDepth.kr(0));
	
	phase = Phasor.ar(0, 100 * SampleDur.ir);
	sig = OscOS.ar(
		bufnum: b,
		phase: phase,
		buf_divs: b.numFrames / 2048,
		buf_loc: tableIndex,
		oversample: 2
	);
	
	sig!2 * 0.1;
}.play;
)

x.set(\modDepth, 1);
```

**Comment by spluta** [comment]
What is your buffer when this happens? I still can't duplicate the error.

**Comment by jamshark70** [comment]
> Do you have the same issue with OscOS3:

Sorry, I missed that question. Yes, I do get the same crash.

For me, it doesn't make a difference whether buf_loc is < 1 or == 1 initially -- it always crashes when buf_loc goes too high.

> I wonder if I fixed this since you downloaded the library?

I'm building from source. It turns out that I was missing some changes, but merging from upstream and rebuilding didn't fix the crashes.

**Comment by dietcv** [comment]
The latest Update, fixes the bug for me! Many thanks!

**Comment by jamshark70** [comment]
> The latest Update, fixes the bug for me! Many thanks!

Fixed on my machine too! Great!
